"""add_detailed_schedule_and_remove_old_business_hours

Revision ID: ea19f15edf03
Revises: a5c1b36e2186
Create Date: 2025-05-26 18:42:42.946667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea19f15edf03'
down_revision: Union[str, None] = 'a5c1b36e2186'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operating_hours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('open_time', sa.Time(), nullable=True),
    sa.Column('close_time', sa.Time(), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operating_hours_day_of_week'), 'operating_hours', ['day_of_week'], unique=False)
    op.create_index(op.f('ix_operating_hours_id'), 'operating_hours', ['id'], unique=False)
    op.create_table('special_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('open_time', sa.Time(), nullable=True),
    sa.Column('close_time', sa.Time(), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_special_days_date'), 'special_days', ['date'], unique=False)
    op.create_index(op.f('ix_special_days_id'), 'special_days', ['id'], unique=False)
    op.drop_column('businesses', 'opens_at')
    op.drop_column('businesses', 'closes_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('closes_at', sa.TIME(), nullable=True))
    op.add_column('businesses', sa.Column('opens_at', sa.TIME(), nullable=True))
    op.drop_index(op.f('ix_special_days_id'), table_name='special_days')
    op.drop_index(op.f('ix_special_days_date'), table_name='special_days')
    op.drop_table('special_days')
    op.drop_index(op.f('ix_operating_hours_id'), table_name='operating_hours')
    op.drop_index(op.f('ix_operating_hours_day_of_week'), table_name='operating_hours')
    op.drop_table('operating_hours')
    # ### end Alembic commands ###
